[project]
name = "function-calling-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.3.0",
    "gradio>=5.49.1",
    "mlx-lm>=0.28.3",
    "rich>=14.2.0",
    "mcp>=1.3.2",
    "requests>=2.32.3",
]
